#this is just a simple playbook for performing some tests
#it's the one i'm using for jenkins to launch as the final stage
---
    -
        hosts: all
        tasks:
            -
                name: update package list
                become: yes
                apt: update_cache=yes cache_valid_time=36000
    - 
        hosts: webservers
        remote_user: root
        become: yes
        tasks:          
            - 
                name: instalar tomcat
                apt:
                    name: tomcat7
                    state: present
            

            - 
                name: Restart service tomcat7
                service:
                    name: tomcat7
                    state: restarted

#pip e lxml are necessary to download the artefact
            -
                name: Install PIP
                apt: 
                    name: python-pip
                    state: present

            -
                name: Install lxml
                pip:
                    name: lxml
            -
                name: get latest todd
                maven_artifact:
                    group_id: pt.isep.cogsi
                    artifact_id: cogsiP5
                    repository_url: 'http://192.168.20.12:8081/repository/maven-snapshots/'
                    username: admin
                    password: pass1234
                    dest: /root/

            

            -
                name: ativa nrpe
                shell: "/etc/init.d/nagios-nrpe-server restart"
                

    - 
        hosts: server1
        remote_user: root
        become: yes
        tasks:          
            - 
                name: update etc hosts
                shell: "echo \"192.168.20.20 server1 >> /etc/hosts\""
            -
                name: ativar jmx remote
                shell: echo "CATALINA_OPTS=\"-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.rmi.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=192.168.20.20 -Dcom.sun.management.jmxremote.host=192.168.20.20\"" > /usr/share/tomcat7/bin/setenv.sh
            

            -
                name: executar todd server
                shell: "java -Dcom.sun.management.jmxremote.port=10500 -Dcom.sun.management.jmxremote.rmi.port=10500 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.20.20 -Dcom.sun.management.jmxremote.host=192.168.20.20 -cp /root/cogsiP5-latest.jar net.jnjmx.todd.Server &"

            
    - 
        hosts: server2
        remote_user: root
        become: yes
        tasks:          
            - 
                name: update etc hosts
                shell: "echo \"192.168.20.21 server1 >> /etc/hosts\""
            -
                name: ativar jmx remote
                shell: echo "CATALINA_OPTS=\"-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.rmi.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=192.168.20.21 -Dcom.sun.management.jmxremote.host=192.168.20.21\"" > /usr/share/tomcat7/bin/setenv.sh
            -
                name: executar todd server
                shell: "java -Dcom.sun.management.jmxremote.port=10500 -Dcom.sun.management.jmxremote.rmi.port=10500 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.20.21 -Dcom.sun.management.jmxremote.host=192.168.20.21 -cp /root/cogsiP5-latest.jar net.jnjmx.todd.Server &"

            
    - 
        hosts: webservers
        remote_user: root
        become: yes
        tasks:          
        
            - 
                name: Restart service tomcat7
                service:
                    name: tomcat7
                    state: restarted          
            -
                name: executar todd client
                shell: "java -cp /root/cogsiP5-latest.jar net.jnjmx.todd.ClientApp4 &"
